### ISSUE TITLE
Custom class breaks html tag

### ISSUE THREAD

**Issue by juliawarnke** [visuellverstehen/markdown-to-html#9]
the `pre-tag` will be torn apart like this, when adding custom classes to `pre` and `p`:

![Bildschirmfoto 2021-07-27 um 09 59 31](https://user-images.githubusercontent.com/44929138/127118256-c4f51f81-cc0a-4f4a-bd09-8651f0598398.png)

How it should look like:
![Bildschirmfoto 2021-07-27 um 10 04 36](https://user-images.githubusercontent.com/44929138/127118965-6540a932-2e00-403d-87a2-69afd8dfc0d9.png)

**Markdown config:**
` 'styles' => [
        'default' => [
            'pre' => 'border overflow-auto p-3',
            'p' => 'mb-4',
        ],
    ],`

**Comment by jonassiewertsen** [comment]
Good catch!

It's related, as we don't check for any allowed characters after the classname. 

Right now, the class replacement does work via a simple `str_replace`. It will be solved, by using a stable regex expression, as this can resolve #10 .
